### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by Lily-2002** [polimi-ispl/camera-model-identification-with-cnn#2]
Do you have a copy of the Dresden Image Database? The urls of these images are invalid now, and I can't download the dataset. Thank you very much! My email is 1062076461@qq.com

**Comment by bestagini** [comment]
We have no rights over the Dresden Image Database, so we cannot share it. Please, contact the dataset's owners (see https://dl.acm.org/doi/10.1145/1774088.1774427)
